### ISSUE TITLE
design of sidepanel does not show up in docs

### ISSUE THREAD

**Issue by LeaSeep** [ICB-DCM/cOmicsArt#313]
I think this is an issue with the spilt of the page - maybe simply remove that and paste picture in between.

**Comment by LeaSeep** [comment]
https://icb-dcm.github.io/cOmicsArt/interface-details.html 
You can see that there is a broken image, an image of the sidepanel should be visible here. 
In the backend we have here a split layout, so in theory the picture should be visible beside the text - this does not work. Would be fine to remove the split layout and paste the picture simply beneath the corresponding text

**Comment by anikde07** [comment]
![Screenshot 2024-11-05 103556](https://github.com/user-attachments/assets/16860056-2cc9-4574-890d-b0777c7fba9e)
Could you highlight which image you are referring to? Since for me I can see both the logo in the side panel and the comic in the main panel

**Comment by LeaSeep** [comment]
<img width="776" alt="Screenshot 2024-11-05 at 11 03 40" src="https://github.com/user-attachments/assets/42555d1a-9224-4599-827d-2736cb512e5b">
Here you can see the broken image Icon

**Comment by anikde07** [comment]
![Screenshot 2024-11-05 135325](https://github.com/user-attachments/assets/c32ea8e1-9eba-4ecf-94fe-38592573b92a)
Ah I see. For me there is no broken image showing up. That is why I was a bit confused
