### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by PaulJonasJost** [ICB-DCM/cOmicsArt#357]
- [x] Matrix not Full rank
- [x] Sig Ana Bug: One comparison -> Volcano -> add comparion -> get sig ana -> Bug
- [x] App has crashed Info
- [x] (if possible) Reload button even if crashed otherwise just reload button
- [x] DESeq proc -> Anderes process -> Sig Ana -> Bug (weil nur Liga ana Möglichkeit)
- [x] if few genes selected and then DEseq, error pops up but waiter does not dissapear - no chance to proceed

**Comment by LeaSeep** [comment]
tried could of things for reload button - rather hard. Would leave out - as now crash is really obvious see: #368

**Comment by PaulJonasJost** [comment]
> tried could of things for reload button - rather hard. Would leave out - as now crash is really obvious see: #368

added a refresh button to the crash page, marked as resolved again 👍🏼

**Comment by PaulJonasJost** [comment]
Sig Ana bug cannot be reproduced
