### ISSUE TITLE
Very first time: Docu + Tutorial (cookie usage)

### ISSUE THREAD

**Issue by LeaSeep** [ICB-DCM/cOmicsArt#364]
I do not know if we still want this based on the solution provided now. (currently still on branch https://github.com/ICB-DCM/cOmicsArt/tree/firstTimeUserHelp )

**Comment by PaulJonasJost** [comment]
I think we do, If we save some cookies that would alow people to disable the tutorial as default opener, that again saves a click. I think that could get on peoples nerves longterm. I find it mildly inconvenient for myself right now (but essential for newcomers)

**Comment by LeaSeep** [comment]
ok - will add a cookie the user can toggle on or of on the very first tab (will at least try :D )
