### ISSUE TITLE
Documentatation refinement needed

### ISSUE THREAD

**Issue by LeaSeep** [ICB-DCM/cOmicsArt#365]
More details in Documentation needed for
- [x] Designing DESeq formula 
- [x] More information about pre-processing  Procedures 
- [ ] Sample Correlation
- [x] TakingNotedMD_help.md content should be also put to general Help  unter Features Across Tabs at Interface Details
- [x] Significance Analysis md

(Note the info is within the QuestionMark help md.files but not in general doc)
Aim: Reduce text weight on Question marks => should be 'short help'

**Comment by PaulJonasJost** [comment]
@LeaSeep looked at the sample correlation, not sure what more info you would like unless we should write the actual formulas? I trimmed down sample correlation info in helper marks as it was too extensive.

**Comment by PaulJonasJost** [comment]
now should also close #365

**Comment by LeaSeep** [comment]
Just double cheched as well cannot tell anymore would mark as solved and this issue as fixed but not releases
